import type { ConfigPlugin, ExportedConfig } from "expo/config-plugins";
import fs from "fs";
import path from "path";

import { withAndroidIconAliases, withAndroidIconResources } from "./android";
import {
  withAppleAlternateIcons,
  withAppleGlassIconAssets,
  withAppleGlassIconBuildSettings,
  withAppleIconAssets,
  withAppleIconImages,
} from "./apple";
import { normalizeIconSet, resolveAppleVariants } from "./icons";
import type { IconPluginInput, IconSet } from "./types";

/**
 * Config plugin entry point. Wires up the per-platform sub-plugins from a
 * single icon declaration and keeps the shipped `IconName` type in sync.
 */
const withDynamicIcon: ConfigPlugin<IconPluginInput> = (config, input) => {
  const icons = normalizeIconSet(input);
  const variants = resolveAppleVariants(Boolean(config.ios?.supportsTablet));
  const props = { icons, variants };

  config = withTypedIconNames(config, icons);

  config = withAppleIconAssets(config, props);
  config = withAppleAlternateIcons(config, props);
  config = withAppleIconImages(config, props);
  config = withAppleGlassIconAssets(config, props);
  config = withAppleGlassIconBuildSettings(config, props);

  config = withAndroidIconAliases(config, icons);
  config = withAndroidIconResources(config, icons);

  return config;
};

/** File the plugin writes into the project root; gitignore it like `expo-env.d.ts`. */
export const ICON_TYPES_FILE = "expo-app-icon-env.d.ts";

/**
 * Declaration that types `IconName` to the configured keys: a module augmentation of the
 * registry in `expo-app-icon/build/types` — the module that declares it, which is what
 * `IconName` in `build/index.d.ts` reads. (Augmenting `"expo-app-icon"` itself would merge
 * into a different, unrelated interface and leave `IconName` as `string`.)
 */
export function renderIconTypes(names: readonly string[]): string {
  const union = names.map((name) => JSON.stringify(name)).join(" | ");
  return [
    "// Generated by expo-app-icon from the plugin config — do not edit; gitignore it like expo-env.d.ts.",
    'import "expo-app-icon";',
    "",
    'declare module "expo-app-icon/build/types" {',
    "  interface DynamicAppIconRegistry {",
    ...(union ? [`    IconName: ${union};`] : []),
    "  }",
    "}",
    "",
  ].join("\n");
}

/**
 * Write the project-local `IconName` declaration so `getAppIcon()` / `setAppIcon()` /
 * `useAppIcon()` are typed to the configured keys. The shipped package is never modified,
 * so projects sharing one copy of it (a monorepo) each keep their own union. The file is
 * only rewritten when its content changes, keeping `expo config` idempotent.
 */
function withTypedIconNames(
  config: ExportedConfig,
  icons: IconSet
): ExportedConfig {
  const projectRoot = config._internal?.projectRoot as string | undefined;
  if (!projectRoot) return config;

  const file = path.join(projectRoot, ICON_TYPES_FILE);
  const content = renderIconTypes(Object.keys(icons));
  let current: string | undefined;
  try {
    current = fs.readFileSync(file, "utf8");
  } catch {
    current = undefined;
  }
  if (current !== content) fs.writeFileSync(file, content);

  return config;
}

export default withDynamicIcon;
